package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.beans.beancontext.BeanContext;
import java.util.ArrayList;
import jp.ac.fjb.Sotuken.bean.MyPageFormBean;
import jp.ac.fjb.Sotuken.bean.TweetPostBean;
import jp.ac.fjb.Sotuken.bean.LoginBean;

public final class _004myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<MyPageFormBean> mpfb = (ArrayList) session.getAttribute("TWEET_LIST");

	LoginBean lb = (LoginBean) session.getAttribute("LOGIN_USER");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet/template/styleSheet.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet/template/header.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet/template/headerContent.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet/template/footer.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet/template/form.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet/template/nav.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet/004myPage.css\" type=\"text/css\" />\r\n");
      out.write("<script src=\"js/myPage.js\"></script>\r\n");
      out.write("<!-- <script src=\"js/file.js\"></script>-->\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#photoIco').bind(\"click touchend\", function() {\r\n");
      out.write("\t\t\t$('#selectImage').click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar cnt = 0;\r\n");
      out.write("\tvar btnName = \"☆Good!\";\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\tsetBtnValue(cnt);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction setBtnValue(cnt) {\r\n");
      out.write("\t\tvar btn = document.getElementById(\"firstFavorite\");\r\n");
      out.write("\t\tif(");
      out.print( lb.getUserId() );
      out.write(" != 0000041 ){\r\n");
      out.write("\t\t\tbtn.value = btnName + cnt;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tbtn.value = btnName + 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/*\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\t//ボタンを取得\r\n");
      out.write("\t\tvar targetBtn = documten.getEleentById(\"firstFavorite\");\r\n");
      out.write("\t\t//targetBtnをクリックしたとき\r\n");
      out.write("\t\ttargetBtn.onclick = function(){\r\n");
      out.write("\t\t\tnum++;\r\n");
      out.write("\t\t\ttargetBtn.value = name + num;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//初期設定\r\n");
      out.write("\t\ttargetBtn.value = name+num;\r\n");
      out.write("\t}*/\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction show_html() {\r\n");
      out.write("\t\tif(");
      out.print( lb.getUserId() );
      out.write(" != 0000041 ){\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (document.getElementById) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"goodUserName\").innerHTML = '");
      out.print( lb.getName() );
      out.write("';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>004マイページ画面</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- ヘッダー　-->\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"wrap_header\">\r\n");
      out.write("\t\t\t<div id=\"headerSpace\"></div>\r\n");
      out.write("\t\t\t<!-- 会社のロゴ的なもの -->\r\n");
      out.write("\t\t\t<img id=\"logo\" src=\"img/logo.png\" />\r\n");
      out.write("\t\t\t<div id=\"headerContents\">\r\n");
      out.write("\t\t\t\t<div id=\"headerContentsSpace\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"noticeList\">\r\n");
      out.write("\t\t\t\t\t<!-- 様々なその他の通知  -->\r\n");
      out.write("\t\t\t\t\t<div id=\"various\" class=\"headerList\" >\r\n");
      out.write("\t\t\t\t\t\t<img class=\"icoSize\" src=\"img/various.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 友達追加通知  -->\r\n");
      out.write("\t\t\t\t\t<div id=\"friends\" class=\"headerList\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"icoSize\" src=\"img/friendsIco.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- チャット通知  -->\r\n");
      out.write("\t\t\t\t\t<div id=\"realtimeChat\" class=\"headerList\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"icoSize\" src=\"img/chatIco.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- メール通知  -->\r\n");
      out.write("\t\t\t\t\t<div id=\"message\" class=\"headerList\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"icoSize\" src=\"img/mailIco.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"menuList\">\r\n");
      out.write("\t\t\t\t\t<!-- つぶやきボタン-->\r\n");
      out.write("\t\t\t\t\t<a href=\"MyPageServlet\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tweetPost\" class=\"headerList\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"icoSize\" src=\"img/tweet.png\">\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t\t<!-- 友達検索 -->\r\n");
      out.write("\t\t\t\t\t<a href=\"018UserSearch.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"userSearch\" class=\"headerList\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"icoSize\" src=\"img/memberSearch.png\">\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t\t<!-- ホーム -->\r\n");
      out.write("\t\t\t\t\t<a href=\"MyPageServlet\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"myPage\" class=\"headerList\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"icoSize\" src=\"img/homeIco.png\">\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ヘッダ終了 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- NAV要素 -->\r\n");
      out.write("\t<div id=\"nav\">\r\n");
      out.write("\t\t<div id=\"innerNav\">\r\n");
      out.write("\t\t\t<!-- ********** nav要素のユーザ領域 *********** -->\r\n");
      out.write("\t\t\t<a href=\"020UserInfo.jsp\">\r\n");
      out.write("\t\t\t\t<div id=\"myInformation\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navList\">");
      out.print( lb.getName() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<img id=\"navUserIco\" class=\"ico\" src=\"img/default.png\" />\r\n");
      out.write("\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t<!-- /********** nav要素のユーザ領域 *********** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ********** nav要素のニュース領域 *********** -->\r\n");
      out.write("\t\t\t<!-- ***************************************************************************** -->\r\n");
      out.write("\t\t\t<!-- ***************************************************************************** -->\r\n");
      out.write("\t\t\t<!-- ***************************************************************************** -->\r\n");
      out.write("\t\t\t<a href=\"MyPageServlet\">\r\n");
      out.write("\t\t\t\t<div id=\"newFeed\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navList\">ニュース</div>\r\n");
      out.write("\t\t\t\t\t<img class=\"ico\" src=\"img/newsPaper.png\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t<!-- /********** nav要素のニュース領域 *********** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ********** nav要素の画像領域 *********** -->\r\n");
      out.write("\t\t\t<a href=\"MyPageServlet\">\r\n");
      out.write("\t\t\t\t<div id=\"album\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navList\">アルバム</div>\r\n");
      out.write("\t\t\t\t\t<img class=\"ico\" src=\"img/album.png\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t<!-- /********** nav要素のニュース領域 *********** -->\r\n");
      out.write("\t\t\t<!-- ***************************************************************************** -->\r\n");
      out.write("\t\t\t<!-- ***************************************************************************** -->\r\n");
      out.write("\t\t\t<!-- ***************************************************************************** -->\r\n");
      out.write("\t\t\t<!-- ********** nav要素のメール領域 *********** -->\r\n");
      out.write("\t\t\t<a href=\"MailServlet\">\r\n");
      out.write("\t\t\t\t<div id=\"mail\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navList\">メール</div>\r\n");
      out.write("\t\t\t\t\t<img class=\"ico\" src=\"img/mail.png\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<!-- /********** nav要素のメール領域 *********** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ********** nav要素のチャット領域 *********** -->\r\n");
      out.write("\t\t\t<a href=\"groupSelectServlet\">\r\n");
      out.write("\t\t\t\t<div id=\"chat\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navList\">チャット</div>\r\n");
      out.write("\t\t\t\t\t<img class=\"ico\" src=\"img/chat.png\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t<!-- /********** nav要素のチャット領域 *********** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ********** nav要素の設定領域 *********** -->\r\n");
      out.write("\t\t\t<a href=\"006personalInformationChange.jsp\">\r\n");
      out.write("\t\t\t\t<div id=\"setting\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navList\">設定</div>\r\n");
      out.write("\t\t\t\t\t<img class=\"ico\" src=\"img/setting.png\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t<!-- /********** nav要素の設定領域 *********** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- メイン　-->\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<!-- ツイートエリアやタイムライン等、全てを含んだ領域  -->\r\n");
      out.write("\t\t<div id=\"timeLine\">\r\n");
      out.write("\t\t\t<!-- コンテンツ開始　 -->\r\n");
      out.write("\t\t\t<div id=\"contents\">\r\n");
      out.write("\t\t\t\t<!-- ********************************************************************** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- つぶやく領域 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"/Sotuken/MyPageServlet\" id=\"postTweet\" method=\"post\" name=\"postTweet\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"userId\" name=\"userId\" value=\"");
      out.print(lb.getUserId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t");
 System.out.println(lb.getUserId()); 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"tweetarea\">\r\n");
      out.write("\t\t\t\t\t\t<!-- つぶやきを投稿するときのツール置き場1 -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"topTweetTools\" class=\"tweetTools\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"spaceBox\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"addImage\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" name=\"tweetImg\" id=\"selectImage\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"photoIco\" src=\"img/photoIco.png\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- つぶやきを投稿するときのツール置き場2終了 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- つぶやく領域　 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<textarea id=\"tweet\" placeholder=\"つぶやく内容を記入\" name=\"tweetContent\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t<!-- つぶやきを投稿するときのツール置き場2 -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"btmTweetTools\" class=\"tweetTools\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"submitBox\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" id=\"submit\" value=\"投稿\" class=\"button\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"spaceBox\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- つぶやきを投稿するときのツール置き場2 終了 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"/Sotuken/MyPageServlet\" id=\"textareaDataForm\"\r\n");
      out.write("\t\t\t\t\tname=\"textateaDataForm\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"textareaData\" name=\"textareaData\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<!-- /つぶやく領域 -->\r\n");
      out.write("\t\t\t\t<!-- ここは、タイムラインに表示される領域 -->\r\n");
      out.write("\t\t\t\t<div class=\"outWrapTimeLineBox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrapTimeLineBox\" id=\"wrapTimeLineBoxTop\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- **************************先頭のつぶやきの領域************************** -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"timeLineBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nameArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									//先頭のつぶやきを取得するために、リストのなかの0番目を表示
									MyPageFormBean myPage = mpfb.get(0);
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(myPage.getUserName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(myPage.getTweet());
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeAndPost\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"postName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t部署名:");
      out.print(myPage.getPostName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(myPage.getSendTime());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"shareArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" class=\"favorite\" id=\"firstFavorite\" onclick=\"setBtnValue(++cnt);disabled = true;show_html();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--  <img class=\"favorite\" id=\"firstFavorite\" src=\"img/good.png\"  onclick=\"favorite()\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"comment\" src=\"img/comment.png\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"goodCountArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"goodCount\"><span id=\"goodUserName\" ></span></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"commentArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"commentContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentUserName\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- コメントしたユーザのアイコン -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"commentIcon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"commentUserIconSize\" src=\"img/userIcoWhite.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- つぶやき投稿者のユーザアイコン -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"userImage\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"userImageSize\" src=\"");
      out.print(myPage.getUserIco());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\tfunction favorite(){\r\n");
      out.write("\t\t\t\t\t\t\tvar Id;\r\n");
      out.write("\t\t\t\t\t\t\t//Id = obj.elements.id;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementsByClassName(\"favorite\");\r\n");
      out.write("\t\t\t\t\t\t\tId = \"");
      out.print(myPage.getTweetId() );
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\twindow.alert(Id);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<!-- **************************/先頭のつぶやきの領域************************** -->\r\n");
      out.write("\t\t\t\t\t<!-- **************************先頭以降のつぶやきの領域part1************************** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						myPage = mpfb.get(1);
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"wrapTimeLineBox\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"timeLineBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nameArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- ユーザID -->\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(myPage.getUserName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(myPage.getTweet());
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeAndPost\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"postName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t部署名:");
      out.print(myPage.getPostName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(myPage.getSendTime());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"shareArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" class=\"favorite\"  value=\"☆Good! 1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <img class=\"favorite\" src=\"img/good.png\" onclick=\"favorite()\" > -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"comment\" src=\"img/comment.png\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"goodCountArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"goodCount\">赤木　貴宣</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"commentArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"commentContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"commentUserName\">太郎 山田</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tコメントをしてみました。よろしくお願いいたします。<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- コメントしたユーザのアイコン -->\r\n");
      out.write("\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"commentIcon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"commentUserIconSize\" src=\"img/userIcoWhite.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"userImage\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"userImageSize\" src=\"");
      out.print(myPage.getUserIco());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- **************************/先頭以降のつぶやきの領域part1************************** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- **************************先頭以降のつぶやきの領域part2************************** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						for (int i = 2; i < mpfb.size(); i++) {

							myPage = mpfb.get(i);

					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"wrapTimeLineBox\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"timeLineBox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nameArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- ユーザID -->\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(myPage.getUserName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(myPage.getTweet());
      out.write("<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeAndPost\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"postName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t部署名:");
      out.print(myPage.getPostName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(myPage.getSendTime());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"shareArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" class=\"favorite\"  value=\"☆Good! 0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <img class=\"favorite\" src=\"img/good.png\" onclick=\"favorite()\" ");
      out.print( myPage.getTweetId() );
      out.write(' ');
      out.print( myPage.getUserId() );
      out.write(">  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"comment\" src=\"img/comment.png\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"goodCountArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"goodCount\">3件のGood!があります。</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"commentArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"commentContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentUserName\">太郎 山田</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"commentText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tコメントをしてみました。よろしくお願いいたします。<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- コメントしたユーザのアイコン -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"commentIcon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"commentUserIconSize\" src=\"img/userIcoWhite.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"userImage\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"userImageSize\" src=\"");
      out.print(myPage.getUserIco());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- **************************/先頭以降のつぶやきの領域part2************************** -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /ここは、タイムラインに表示される領域 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- コンテンツ終了 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- フッター -->\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<div id=\"wrap_footer\">\r\n");
      out.write("\t\t\t\t<!-- フッターはここに書く　 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
